# Анализ поведения посетителей интернет-магазина

Цель: исследовать путь от просмотра товара до добавления в корзину и покупки.
Данные: Retailrocket Ecommerce Dataset, файл events.csv.

In [17]:
import kagglehub
import pandas as pd


events_path = kagglehub.dataset_download(
    "retailrocket/ecommerce-dataset",
    path="events.csv"
)


print("Path to events.csv file:", events_path)
events = pd.read_csv(events_path)
events.head()

Path to events.csv file: /Users/mikhailzayats/.cache/kagglehub/datasets/retailrocket/ecommerce-dataset/versions/2/events.csv

       timestamp  visitorid event  itemid  transactionid
0  1433221332117     257597  view  355908            NaN
1  1433224214164     992329  view  248676            NaN
2  1433221999827     111016  view  318965            NaN
3  1433221955914     483717  view  253185            NaN
4  1433221337106     951259  view  367447            NaN

In [18]:
events.dtypes

timestamp          int64
visitorid          int64
event                str
itemid             int64
transactionid    float64
dtype: object

In [19]:
events["event"].unique()

<StringArray>
['view', 'addtocart', 'transaction']
Length: 3, dtype: str

In [20]:
events.isna().sum()

timestamp              0
visitorid              0
event                  0
itemid                 0
transactionid    2733644
dtype: int64

In [21]:
events.groupby("event")["transactionid"].apply(lambda column: column.isna().sum())

event
addtocart        69332
transaction          0
view           2664312
Name: transactionid, dtype: int64

In [22]:
events["event_time"] = pd.to_datetime(
    events["timestamp"],
    unit="ms",
    utc=True
)

events[["timestamp", "event_time"]].head()

       timestamp                       event_time
0  1433221332117 2015-06-02 05:02:12.117000+00:00
1  1433224214164 2015-06-02 05:50:14.164000+00:00
2  1433221999827 2015-06-02 05:13:19.827000+00:00
3  1433221955914 2015-06-02 05:12:35.914000+00:00
4  1433221337106 2015-06-02 05:02:17.106000+00:00

In [23]:
events["event_time"].min(), events["event_time"].max()

(Timestamp('2015-05-03 03:00:04.384000+0000', tz='UTC'),
 Timestamp('2015-09-18 02:59:47.788000+0000', tz='UTC'))